name: Automatyczne Testy (CI)
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Pobranie kodu
        uses: actions/checkout@v4

      - name: Instalacja Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalacja paczek (Frontend)
        working-directory: ./project_tan_stack
        run: npm install

      - name: Uruchomienie testów logiki (Vitest)
        working-directory: ./project_tan_stack
        run: npm run test -- --run

  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Pobranie kodu
        uses: actions/checkout@v4

      - name: Instalacja Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalacja paczek (Backend)
        working-directory: ./backend
        run: npm install
      - name: Sprawdzenie kompilacji backendu
        working-directory: ./backend
        run: npx tsc --noEmit